import { Injectable } from '@nestjs/common';
import { PrismaService } from 'src/prisma/prisma.service';
import { SocketService } from 'src/socket/socket.service';

export class CreateMessageDto {
  content: string;
  type: string;
  roomId: string;
  id: string; // Optional ID, can be generated by the database
}

export class ReadMessageDto {
  messageId: string;
  roomId: string; // Assuming you need roomId to identify the message in a room
}

@Injectable()
export class MessageService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly socketService: SocketService, // Assuming you have a socket service for emitting events
  ) {}

  async create(dto: CreateMessageDto, senderId) {
    const r = await this.prisma.message.create({
      data: {
        id: dto.id,
        content: dto.content,
        type: dto.type,
        senderId: senderId,
        roomId: dto.roomId,
      },
    });
    this.socketService.emitToRoom('message:created', r, dto.roomId);
    return {
      data: r,
      message: 'Message created successfully',
      status: 'success',
      code: 201,
    };
  }

  async find(roomId: string) {
    const res = await this.prisma.message.findMany({
      where: {
        roomId: roomId,
      },
      orderBy: {
        createdAt: 'desc',
      },
    });

    return {
      data: res,
      message: 'Messages retrieved successfully',
      status: 'success',
      code: 200,
    };
  }

  readMessage(readMessageDto: ReadMessageDto, userId: string) {
    // this.messages = [];
    return this.prisma.userRoom.update({
      where: {
        userId_roomId_unique: {
          userId: userId,
          roomId: readMessageDto.roomId,
        },
      },
      data: {
        lastmessageId: readMessageDto.messageId,
        lastReadAt: new Date(),
      },
    });
  }

  deleteMessage(id: string) {
    return this.prisma.message.delete({
      where: { id },
    });
  }
  updateMessage(id: string, dto: CreateMessageDto) {
    return this.prisma.message.update({
      where: { id },
      data: {
        content: dto.content,
        type: dto.type,
      },
    });
  }
}
